language: python
python:
- '2.7'
install: pip install --allow-external argparse -r requirements.txt
script: nosetests
deploy:
  provider: pypi
  user: lsamaha
  password:
    secure: Y45II57WGnB8fm3yRBpVH9k1i/hSKbjpGazcVAfvwyzefFpGL5U/xa9xA4NRWay2WoS8pVMiyTRR7so4Ujv8Jo+aUOWw++nlkamYRF6pvMjPJQe0NTF0JqWfz+KnI8uxZFw2XcHrqBu4bX59TALXTko9vogNneBSqi9rV2WvQgo=
  on:
    repo: lsamaha/dervish
    all_branches: true
